/*
  +----------------------------------------------------------------------+
  | PHP Version 5                                                        |
  +----------------------------------------------------------------------+
  | Copyright (c) 1997-2013 The PHP Group                                |
  +----------------------------------------------------------------------+
  | This source file is subject to version 3.01 of the PHP license,      |
  | that is bundled with this package in the file LICENSE, and is        |
  | available through the world-wide-web at the following url:           |
  | http://www.php.net/license/3_01.txt                                  |
  | If you did not receive a copy of the PHP license and are unable to   |
  | obtain it through the world-wide-web, please send a note to          |
  | license@php.net so we can mail you a copy immediately.               |
  +----------------------------------------------------------------------+
  | Author: Joe Watkins <joe.watkins@live.co.uk>                         |
  +----------------------------------------------------------------------+
*/
static explain_opcode_t opcodes[]= {
	EXPLAIN_OPCODE_NAME(ZEND_NOP),
	EXPLAIN_OPCODE_NAME(ZEND_ADD),
	EXPLAIN_OPCODE_NAME(ZEND_SUB),
	EXPLAIN_OPCODE_NAME(ZEND_MUL),
	EXPLAIN_OPCODE_NAME(ZEND_DIV),
	EXPLAIN_OPCODE_NAME(ZEND_MOD),
	EXPLAIN_OPCODE_NAME(ZEND_SL),
	EXPLAIN_OPCODE_NAME(ZEND_SR),
	EXPLAIN_OPCODE_NAME(ZEND_CONCAT),
	EXPLAIN_OPCODE_NAME(ZEND_BW_OR),
	EXPLAIN_OPCODE_NAME(ZEND_BW_AND),
	EXPLAIN_OPCODE_NAME(ZEND_BW_XOR),
	EXPLAIN_OPCODE_NAME(ZEND_BW_NOT),
	EXPLAIN_OPCODE_NAME(ZEND_BOOL_NOT),
	EXPLAIN_OPCODE_NAME(ZEND_BOOL_XOR),
	EXPLAIN_OPCODE_NAME(ZEND_IS_IDENTICAL),
	EXPLAIN_OPCODE_NAME(ZEND_IS_NOT_IDENTICAL),
	EXPLAIN_OPCODE_NAME(ZEND_IS_EQUAL),
	EXPLAIN_OPCODE_NAME(ZEND_IS_NOT_EQUAL),
	EXPLAIN_OPCODE_NAME(ZEND_IS_SMALLER),
	EXPLAIN_OPCODE_NAME(ZEND_IS_SMALLER_OR_EQUAL),
	EXPLAIN_OPCODE_NAME(ZEND_CAST),
	EXPLAIN_OPCODE_NAME(ZEND_QM_ASSIGN),
	EXPLAIN_OPCODE_NAME(ZEND_ASSIGN_ADD),
	EXPLAIN_OPCODE_NAME(ZEND_ASSIGN_SUB),
	EXPLAIN_OPCODE_NAME(ZEND_ASSIGN_MUL),
	EXPLAIN_OPCODE_NAME(ZEND_ASSIGN_DIV),
	EXPLAIN_OPCODE_NAME(ZEND_ASSIGN_MOD),
	EXPLAIN_OPCODE_NAME(ZEND_ASSIGN_SL),
	EXPLAIN_OPCODE_NAME(ZEND_ASSIGN_SR),
	EXPLAIN_OPCODE_NAME(ZEND_ASSIGN_CONCAT),
	EXPLAIN_OPCODE_NAME(ZEND_ASSIGN_BW_OR),
	EXPLAIN_OPCODE_NAME(ZEND_ASSIGN_BW_AND),
	EXPLAIN_OPCODE_NAME(ZEND_ASSIGN_BW_XOR),
	EXPLAIN_OPCODE_NAME(ZEND_PRE_INC),
	EXPLAIN_OPCODE_NAME(ZEND_PRE_DEC),
	EXPLAIN_OPCODE_NAME(ZEND_POST_INC),
	EXPLAIN_OPCODE_NAME(ZEND_POST_DEC),
	EXPLAIN_OPCODE_NAME(ZEND_ASSIGN),
	EXPLAIN_OPCODE_NAME(ZEND_ASSIGN_REF),
	EXPLAIN_OPCODE_NAME(ZEND_ECHO),
#ifdef ZEND_PRINT
	EXPLAIN_OPCODE_NAME(ZEND_PRINT),
#else
	EXPLAIN_OPCODE_NAME(ZEND_NOP),
#endif
	EXPLAIN_OPCODE_NAME(ZEND_JMP),
	EXPLAIN_OPCODE_NAME(ZEND_JMPZ),
	EXPLAIN_OPCODE_NAME(ZEND_JMPNZ),
	EXPLAIN_OPCODE_NAME(ZEND_JMPZNZ),
	EXPLAIN_OPCODE_NAME(ZEND_JMPZ_EX),
	EXPLAIN_OPCODE_NAME(ZEND_JMPNZ_EX),
	EXPLAIN_OPCODE_NAME(ZEND_CASE),
#ifdef ZEND_SWITCH_FREE
	EXPLAIN_OPCODE_NAME(ZEND_SWITCH_FREE),
#else
	EXPLAIN_OPCODE_NAME(ZEND_NOP),
#endif
	EXPLAIN_OPCODE_NAME(ZEND_BRK),
	EXPLAIN_OPCODE_NAME(ZEND_CONT),
	EXPLAIN_OPCODE_NAME(ZEND_BOOL),
#if PHP_VERSION_ID >= 70000
	EXPLAIN_OPCODE_NAME(ZEND_FAST_CONCAT),
	EXPLAIN_OPCODE_NAME(ZEND_ROPE_INIT),
	EXPLAIN_OPCODE_NAME(ZEND_ROPE_ADD),
	EXPLAIN_OPCODE_NAME(ZEND_ROPE_END),
#else
	EXPLAIN_OPCODE_NAME(ZEND_INIT_STRING),
	EXPLAIN_OPCODE_NAME(ZEND_ADD_CHAR),
	EXPLAIN_OPCODE_NAME(ZEND_ADD_STRING),
	EXPLAIN_OPCODE_NAME(ZEND_ADD_VAR),
#endif
	EXPLAIN_OPCODE_NAME(ZEND_BEGIN_SILENCE),
	EXPLAIN_OPCODE_NAME(ZEND_END_SILENCE),
	EXPLAIN_OPCODE_NAME(ZEND_INIT_FCALL_BY_NAME),
	EXPLAIN_OPCODE_NAME(ZEND_DO_FCALL),
#if PHP_VERSION_ID >= 70000
	EXPLAIN_OPCODE_NAME(ZEND_INIT_FCALL),
#else
	EXPLAIN_OPCODE_NAME(ZEND_DO_FCALL_BY_NAME),
#endif
	EXPLAIN_OPCODE_NAME(ZEND_RETURN),
	EXPLAIN_OPCODE_NAME(ZEND_RECV),
	EXPLAIN_OPCODE_NAME(ZEND_RECV_INIT),
	EXPLAIN_OPCODE_NAME(ZEND_SEND_VAL),
	EXPLAIN_OPCODE_NAME(ZEND_SEND_VAR),
	EXPLAIN_OPCODE_NAME(ZEND_SEND_REF),
	EXPLAIN_OPCODE_NAME(ZEND_NEW),
	EXPLAIN_OPCODE_NAME(ZEND_INIT_NS_FCALL_BY_NAME),
	EXPLAIN_OPCODE_NAME(ZEND_FREE),
	EXPLAIN_OPCODE_NAME(ZEND_INIT_ARRAY),
	EXPLAIN_OPCODE_NAME(ZEND_ADD_ARRAY_ELEMENT),
	EXPLAIN_OPCODE_NAME(ZEND_INCLUDE_OR_EVAL),
	EXPLAIN_OPCODE_NAME(ZEND_UNSET_VAR),
	EXPLAIN_OPCODE_NAME(ZEND_UNSET_DIM),
	EXPLAIN_OPCODE_NAME(ZEND_UNSET_OBJ),
#if PHP_VERSION_ID >= 70000
	EXPLAIN_OPCODE_NAME(ZEND_FE_RESET_R),
	EXPLAIN_OPCODE_NAME(ZEND_FE_FETCH_R),
#else
	EXPLAIN_OPCODE_NAME(ZEND_FE_RESET),
	EXPLAIN_OPCODE_NAME(ZEND_FE_FETCH),
#endif
	EXPLAIN_OPCODE_NAME(ZEND_EXIT),
	EXPLAIN_OPCODE_NAME(ZEND_FETCH_R),
	EXPLAIN_OPCODE_NAME(ZEND_FETCH_DIM_R),
	EXPLAIN_OPCODE_NAME(ZEND_FETCH_OBJ_R),
	EXPLAIN_OPCODE_NAME(ZEND_FETCH_W),
	EXPLAIN_OPCODE_NAME(ZEND_FETCH_DIM_W),
	EXPLAIN_OPCODE_NAME(ZEND_FETCH_OBJ_W),
	EXPLAIN_OPCODE_NAME(ZEND_FETCH_RW),
	EXPLAIN_OPCODE_NAME(ZEND_FETCH_DIM_RW),
	EXPLAIN_OPCODE_NAME(ZEND_FETCH_OBJ_RW),
	EXPLAIN_OPCODE_NAME(ZEND_FETCH_IS),
	EXPLAIN_OPCODE_NAME(ZEND_FETCH_DIM_IS),
	EXPLAIN_OPCODE_NAME(ZEND_FETCH_OBJ_IS),
	EXPLAIN_OPCODE_NAME(ZEND_FETCH_FUNC_ARG),
	EXPLAIN_OPCODE_NAME(ZEND_FETCH_DIM_FUNC_ARG),
	EXPLAIN_OPCODE_NAME(ZEND_FETCH_OBJ_FUNC_ARG),
	EXPLAIN_OPCODE_NAME(ZEND_FETCH_UNSET),
	EXPLAIN_OPCODE_NAME(ZEND_FETCH_DIM_UNSET),
	EXPLAIN_OPCODE_NAME(ZEND_FETCH_OBJ_UNSET),
#if PHP_VERSION_ID >= 70000
	EXPLAIN_OPCODE_NAME(ZEND_FETCH_LIST),
#else
	EXPLAIN_OPCODE_NAME(ZEND_FETCH_DIM_TMP_VAR),
#endif
	EXPLAIN_OPCODE_NAME(ZEND_FETCH_CONSTANT),
	EXPLAIN_OPCODE_NAME(ZEND_GOTO),
	EXPLAIN_OPCODE_NAME(ZEND_EXT_STMT),
	EXPLAIN_OPCODE_NAME(ZEND_EXT_FCALL_BEGIN),
	EXPLAIN_OPCODE_NAME(ZEND_EXT_FCALL_END),
	EXPLAIN_OPCODE_NAME(ZEND_EXT_NOP),
	EXPLAIN_OPCODE_NAME(ZEND_TICKS),
	EXPLAIN_OPCODE_NAME(ZEND_SEND_VAR_NO_REF),
	EXPLAIN_OPCODE_NAME(ZEND_CATCH),
	EXPLAIN_OPCODE_NAME(ZEND_THROW),
	EXPLAIN_OPCODE_NAME(ZEND_FETCH_CLASS),
	EXPLAIN_OPCODE_NAME(ZEND_CLONE),
	EXPLAIN_OPCODE_NAME(ZEND_RETURN_BY_REF),
	EXPLAIN_OPCODE_NAME(ZEND_INIT_METHOD_CALL),
	EXPLAIN_OPCODE_NAME(ZEND_INIT_STATIC_METHOD_CALL),
	EXPLAIN_OPCODE_NAME(ZEND_ISSET_ISEMPTY_VAR),
	EXPLAIN_OPCODE_NAME(ZEND_ISSET_ISEMPTY_DIM_OBJ),
#if PHP_VERSION_ID >= 70000
	EXPLAIN_OPCODE_NAME(ZEND_SEND_VAL_EX),
	EXPLAIN_OPCODE_NAME(ZEND_SEND_VAR),
	EXPLAIN_OPCODE_NAME(ZEND_INIT_USER_CALL),
#else
# ifdef ZEND_IMPORT_FUNCTION
	EXPLAIN_OPCODE_NAME(ZEND_IMPORT_FUNCTION),
# else
	EXPLAIN_OPCODE_NAME(ZEND_NOP),
# endif
# ifdef ZEND_IMPORT_CLASS
	EXPLAIN_OPCODE_NAME(ZEND_IMPORT_CLASS),
# else
	EXPLAIN_OPCODE_NAME(ZEND_NOP),
# endif
# ifdef ZEND_IMPORT_CONST
	EXPLAIN_OPCODE_NAME(ZEND_IMPORT_CONST),
# else
	EXPLAIN_OPCODE_NAME(ZEND_NOP),
# endif
#endif
	EXPLAIN_OPCODE_NAME(ZEND_NOP),
	EXPLAIN_OPCODE_NAME(ZEND_NOP),
#if PHP_VERSION_ID >= 70000
	EXPLAIN_OPCODE_NAME(ZEND_STRLEN),
	EXPLAIN_OPCODE_NAME(ZEND_DEFINED),
	EXPLAIN_OPCODE_NAME(ZEND_TYPE_CHECK),
	EXPLAIN_OPCODE_NAME(ZEND_VERIFY_RETURN_TYPE),
	EXPLAIN_OPCODE_NAME(ZEND_FE_RESET_RW),
	EXPLAIN_OPCODE_NAME(ZEND_FE_FETCH_RW),
	EXPLAIN_OPCODE_NAME(ZEND_FE_FREE),
	EXPLAIN_OPCODE_NAME(ZEND_INIT_DYNAMIC_CALL),
	EXPLAIN_OPCODE_NAME(ZEND_DO_ICALL),
	EXPLAIN_OPCODE_NAME(ZEND_DO_UCALL),
	EXPLAIN_OPCODE_NAME(ZEND_DO_FCALL_BY_NAME),
#else
# ifdef ZEND_ASSIGN_ADD_OBJ
	EXPLAIN_OPCODE_NAME(ZEND_ASSIGN_ADD_OBJ),
# else
	EXPLAIN_OPCODE_NAME(ZEND_NOP),
# endif
# ifdef ZEND_ASSIGN_SUB_OBJ
	EXPLAIN_OPCODE_NAME(ZEND_ASSIGN_SUB_OBJ),
# else
	EXPLAIN_OPCODE_NAME(ZEND_NOP),
# endif
# ifdef ZEND_ASSIGN_MUL_OBJ
	EXPLAIN_OPCODE_NAME(ZEND_ASSIGN_MUL_OBJ),
# else
	EXPLAIN_OPCODE_NAME(ZEND_NOP),
# endif
# ifdef ZEND_ASSIGN_DIV_OBJ
	EXPLAIN_OPCODE_NAME(ZEND_ASSIGN_DIV_OBJ),
# else
	EXPLAIN_OPCODE_NAME(ZEND_NOP),
# endif
# ifdef ZEND_ASSIGN_MOD_OBJ
	EXPLAIN_OPCODE_NAME(ZEND_ASSIGN_MOD_OBJ),
# else
	EXPLAIN_OPCODE_NAME(ZEND_NOP),
# endif
# ifdef ZEND_ASSIGN_SL_OBJ
	EXPLAIN_OPCODE_NAME(ZEND_ASSIGN_SL_OBJ),
# else
	EXPLAIN_OPCODE_NAME(ZEND_NOP),
# endif
# ifdef ZEND_ASSIGN_SR_OBJ
	EXPLAIN_OPCODE_NAME(ZEND_ASSIGN_SR_OBJ),
# else
	EXPLAIN_OPCODE_NAME(ZEND_NOP),
# endif
# ifdef ZEND_ASSIGN_CONCAT_OBJ
	EXPLAIN_OPCODE_NAME(ZEND_ASSIGN_CONCAT_OBJ),
# else
	EXPLAIN_OPCODE_NAME(ZEND_NOP),
# endif
# ifdef ZEND_ASSIGN_BW_OR_OBJ
	EXPLAIN_OPCODE_NAME(ZEND_ASSIGN_BW_OR_OBJ),
# else
	EXPLAIN_OPCODE_NAME(ZEND_NOP),
# endif
# ifdef ZEND_ASSIGN_BW_AND_OBJ
	EXPLAIN_OPCODE_NAME(ZEND_ASSIGN_BW_AND_OBJ),
# else
	EXPLAIN_OPCODE_NAME(ZEND_NOP),
# endif
# ifdef ZEND_ASSIGN_BW_XOR_OBJ
	EXPLAIN_OPCODE_NAME(ZEND_ASSIGN_BW_XOR_OBJ),
# else
	EXPLAIN_OPCODE_NAME(ZEND_NOP),
# endif
#endif
	EXPLAIN_OPCODE_NAME(ZEND_PRE_INC_OBJ),
	EXPLAIN_OPCODE_NAME(ZEND_PRE_DEC_OBJ),
	EXPLAIN_OPCODE_NAME(ZEND_POST_INC_OBJ),
	EXPLAIN_OPCODE_NAME(ZEND_POST_DEC_OBJ),
	EXPLAIN_OPCODE_NAME(ZEND_ASSIGN_OBJ),
	EXPLAIN_OPCODE_NAME(ZEND_OP_DATA),
	EXPLAIN_OPCODE_NAME(ZEND_INSTANCEOF),
	EXPLAIN_OPCODE_NAME(ZEND_DECLARE_CLASS),
	EXPLAIN_OPCODE_NAME(ZEND_DECLARE_INHERITED_CLASS),
	EXPLAIN_OPCODE_NAME(ZEND_DECLARE_FUNCTION),
#if PHP_VERSION_ID >= 70000
	EXPLAIN_OPCODE_NAME(ZEND_YIELD_FROM),
#else
	EXPLAIN_OPCODE_NAME(ZEND_RAISE_ABSTRACT_ERROR),
#endif
	EXPLAIN_OPCODE_NAME(ZEND_DECLARE_CONST),
	EXPLAIN_OPCODE_NAME(ZEND_ADD_INTERFACE),
	EXPLAIN_OPCODE_NAME(ZEND_DECLARE_INHERITED_CLASS_DELAYED),
	EXPLAIN_OPCODE_NAME(ZEND_VERIFY_ABSTRACT_CLASS),
	EXPLAIN_OPCODE_NAME(ZEND_ASSIGN_DIM),
	EXPLAIN_OPCODE_NAME(ZEND_ISSET_ISEMPTY_PROP_OBJ),
	EXPLAIN_OPCODE_NAME(ZEND_HANDLE_EXCEPTION),
	EXPLAIN_OPCODE_NAME(ZEND_USER_OPCODE),
#if PHP_VERSION_ID >= 70000
	EXPLAIN_OPCODE_NAME(ZEND_ASSERT_CHECK),
#else
	EXPLAIN_OPCODE_NAME(ZEND_NOP),
#endif
	EXPLAIN_OPCODE_NAME(ZEND_JMP_SET),
	EXPLAIN_OPCODE_NAME(ZEND_DECLARE_LAMBDA_FUNCTION),
	EXPLAIN_OPCODE_NAME(ZEND_ADD_TRAIT),
	EXPLAIN_OPCODE_NAME(ZEND_BIND_TRAITS),
	EXPLAIN_OPCODE_NAME(ZEND_SEPARATE),
#if PHP_VERSION_ID >= 70000
	EXPLAIN_OPCODE_NAME(ZEND_FETCH_CLASS_NAME),
	EXPLAIN_OPCODE_NAME(ZEND_CALL_TRAMPOLINE),
#else
	EXPLAIN_OPCODE_NAME(ZEND_QM_ASSIGN_VAR),
	EXPLAIN_OPCODE_NAME(ZEND_JMP_SET_VAR),
#endif
#ifdef ZEND_DISCARD_EXCEPTION
	EXPLAIN_OPCODE_NAME(ZEND_DISCARD_EXCEPTION),
#else
  EXPLAIN_OPCODE_NAME(ZEND_NOP),
#endif
#ifdef ZEND_GENERATOR_YIELD
  EXPLAIN_OPCODE_NAME(ZEND_YIELD),
#else
  EXPLAIN_OPCODE_NAME(ZEND_NOP),
#endif
#ifdef ZEND_GENERATOR_RETURN
	EXPLAIN_OPCODE_NAME(ZEND_GENERATOR_RETURN),
#else
  EXPLAIN_OPCODE_NAME(ZEND_NOP),
#endif
#ifdef ZEND_FAST_CALL
	EXPLAIN_OPCODE_NAME(ZEND_FAST_CALL),
#else
  EXPLAIN_OPCODE_NAME(ZEND_NOP),
#endif
#ifdef ZEND_FAST_RET
	EXPLAIN_OPCODE_NAME(ZEND_FAST_RET),
#else
  EXPLAIN_OPCODE_NAME(ZEND_NOP),
#endif
#ifdef ZEND_RECV_VARIADIC
	EXPLAIN_OPCODE_NAME(ZEND_RECV_VARIADIC),
#else
  EXPLAIN_OPCODE_NAME(ZEND_NOP),
#endif
	{NULL, 0, 0}
};
